DELETE http://localhost:3003/api/blogs/62fa95b331effd754a3bd020
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhbGlob255YSIsImlkIjoiNjJmYTk0NDlkMzhmOWFkOGJkMDFiNzIxIiwiaWF0IjoxNjYwNzY2MjI0fQ.MOYrWktpes42Zc5Ft55uVbJQnOSfjp1eqtIXQYhCASY